
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: Wedding_app_development

test:
  <<: *default
  database: wedding_app_test

production:
  <<: *default
  database: Wedding_app_production
  username: Wedding_app
  password: <%= ENV['WEDDING_APP_DATABASE_PASSWORD'] %>
